apiVersion: v1
kind: Service
metadata:
  name: sales-service
  namespace: sales-system
spec:
  type: ClusterIP
  selector:
    app: sales
  ports:
    - name: sales
      port: 3000
      targetPort: sales
    - name: sales-debug
      port: 4000
      targetPort: sales-debug
