apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-pod
  namespace: database-system
spec:
  selector:
    matchLabels:
      app: database
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: database
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
        - name: postgres
          image: postgres:14.5
          resources:
            limits:
              cpu: "1000m" # Up to 1 full core
            requests:
              cpu: "1000m" # Use 1 full core
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db_password
          ports:
            - name: postgres
              containerPort: 5432
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
                - -U
                - postgres
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
                - -U
                - postgres
            initialDelaySeconds: 5
            timeoutSeconds: 1
