apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/sales-pod
patchesStrategicMerge:
- ./service-patch.yaml
images:
  - name: openzipkin
    newName: openzipkin/zipkin
    newTag: "2.23"
